<%@ Page Language="C#" MasterPageFile="~/Site.Master"
    AutoEventWireup="true"
    CodeBehind="CRUDData.aspx.cs"
    Inherits="Budgetly.CRUDData" %>

<asp:Content ID="Content1"
    ContentPlaceHolderID="ContentPlaceHolder1"
    runat="server">

    <style>
        .container {
            max-width: 1200px;
            margin: 20px auto;
            font-family: Arial, sans-serif;
        }
        .table-selector {
            margin: 20px 0;
            padding: 10px;
            background: #f5f5f5;
            border-radius: 5px;
        }
        .grid-container {
            margin-top: 20px;
            overflow-x: auto;
        }
        .grid-view {
            width: 100%;
            border-collapse: collapse;
        }
        .grid-view th {
            background-color: #007bff;
            color: white;
            padding: 8px;
        }
        .grid-view td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        .grid-view tr:hover {
            background-color: #f5f5f5;
        }
    </style>

    <div class="container">

        <h2>CRUD Manager - All Tables</h2>

        <!-- TABLE SELECTOR -->
        <div class="table-selector">
            <label>Select Table:</label>

            <asp:DropDownList ID="ddlTable" runat="server"
                AutoPostBack="true"
                OnSelectedIndexChanged="ddlTable_SelectedIndexChanged"
                Width="260px">

                <asp:ListItem Text="-- Select Table --" Value="" />
                <asp:ListItem Text="Users" />
                <asp:ListItem Text="UserProfiles" />
                <asp:ListItem Text="Subscriptions" />
                <asp:ListItem Text="UserSubscriptions" />
                <asp:ListItem Text="Accounts" />
                <asp:ListItem Text="AccountImages" />
                <asp:ListItem Text="Categories" />
                <asp:ListItem Text="Transactions" />
                <asp:ListItem Text="TransactionAttachments" />
                <asp:ListItem Text="GmailTransactionTracker" />
                <asp:ListItem Text="Income" />
                <asp:ListItem Text="Budgets" />
                <asp:ListItem Text="BudgetEnvelopes" />
                <asp:ListItem Text="BudgetProgress" />
                <asp:ListItem Text="Pets" />
                <asp:ListItem Text="UserPets" />
                <asp:ListItem Text="PetStatusImages" />
                <asp:ListItem Text="Badges" />
                <asp:ListItem Text="UserBadges" />
                <asp:ListItem Text="Challenges" />
                <asp:ListItem Text="UserChallenges" />
                <asp:ListItem Text="LeaderboardStats" />
                <asp:ListItem Text="EcoScores" />
                <asp:ListItem Text="MerchantRules" />
            </asp:DropDownList>

            <asp:Button ID="btnRefresh" runat="server"
                Text="Refresh"
                OnClick="btnRefresh_Click"
                Style="margin-left:10px;" />

            <asp:Label ID="lblMessage" runat="server"
                ForeColor="Green"
                Style="margin-left:10px;" />

            <asp:Label ID="lblError" runat="server"
                ForeColor="Red"
                Style="margin-left:10px;" />
        </div>

        <!-- GRID -->
        <div class="grid-container">
            <asp:GridView ID="gvData" runat="server"
                AutoGenerateColumns="true"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true"
                CssClass="grid-view"
                AllowPaging="true"
                PageSize="10"
                OnRowEditing="gv_RowEditing"
                OnRowUpdating="gv_RowUpdating"
                OnRowDeleting="gv_RowDeleting"
                OnRowCancelingEdit="gv_RowCancel"
                OnPageIndexChanging="gvData_PageIndexChanging">
            </asp:GridView>
        </div>

        <!-- STATS -->
        <div style="margin-top:20px; background:#f0f8ff; padding:10px; border-radius:5px;">
            <h3>Quick Stats</h3>
            <asp:Label ID="lblStats" runat="server" />
        </div>

    </div>

</asp:Content>
